name: 'gsynergy_challenge'
version: '1.0.0'
config-version: 2

profile: 'gsynergy_challenge'  # Ensure this profile is properly configured in profiles.yml

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  gsynergy_challenge:
      staging:
          schema: staging
          materialized: view
          tags: ["staging"]  
      marts:
          materialized: table  
